#pragma once

#include <wrl\client.h>
#include <vector>
#include <list>
#include <sstream>
#include <memory>
#include <iostream>
#include <random>
#include <ctime>
#include <fstream>
#include <utility>
#include <dxgi.h>
#include <d3dcommon.h>
#include <d3d11.h>
#include <DirectXMath.h>
#include <algorithm>
#include <random>
#include <numeric>
#include <functional>
#include <thread>
#include <condition_variable>
#include <atomic>